# syntax=docker/dockerfile:1

FROM node:16 AS base
ENV NODE_ENV=production
WORKDIR /code

COPY ["package.json", "yarn.lock", ".yarnrc.yml", "./"]
COPY [".yarn/", "./.yarn/"]

RUN yarn set version berry
RUN yarn install

COPY . .
RUN yarn build:prod

EXPOSE 3000
CMD [ "yarn", "start:prod" ]
