# syntax=docker/dockerfile:1

FROM node:16 AS base
ENV NODE_ENV=development
WORKDIR /code

COPY ["package.json", "yarn.lock", ".yarnrc.yml", "./"]
COPY [".yarn/", "./.yarn/"]

RUN yarn set version berry
RUN yarn install

COPY . .
RUN yarn build

EXPOSE 3000
CMD [ "yarn", "start" ]
