services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/code/src
      - ./server:/code/server
    ports:
      - 3000:3000 
    command: yarn watch:docker
  